"""Document generation service — creates PDFs for LaunchPad and grants"""
import logging
from typing import Optional

logger = logging.getLogger("arise.docgen")

def generate_business_profile_pdf(business_data: dict, user_data: dict) -> bytes:
    """Generates a business profile summary PDF"""
    # TODO: use reportlab for production PDF generation
    content = f"""
ARISE — Business Profile
========================
Business Name: {business_data.get('business_name', 'N/A')}
Owner: {user_data.get('full_name', 'N/A')}
Sector: {business_data.get('sector', 'N/A')}
Province: {business_data.get('province', 'N/A')}
CIPC Number: {business_data.get('cipc_number', 'Not registered')}
Stage: {business_data.get('stage', 'N/A')}
Description: {business_data.get('description', 'N/A')}
ECS Score: {user_data.get('ecs_score', 0)}

Generated by ARISE · Powered by Huawei Cloud
    """
    return content.encode('utf-8')

def generate_grant_application_pdf(grant_data: dict, user_data: dict, business_data: dict) -> bytes:
    """Generates a pre-filled grant application PDF"""
    content = f"""
ARISE — Grant Application Draft
================================
Grant Program: {grant_data.get('name', 'N/A')}
Funder: {grant_data.get('funder', 'N/A')}
Amount Requested: R{grant_data.get('funding_amount_requested', 'N/A')}

APPLICANT DETAILS
Applicant Name: {user_data.get('full_name', 'N/A')}
Email: {user_data.get('email', 'N/A')}
Province: {user_data.get('province', 'N/A')}
ID Number: [From verified TrustID]

BUSINESS DETAILS
Business Name: {business_data.get('business_name', 'N/A')}
CIPC Registration: {business_data.get('cipc_number', 'N/A')}
Sector: {business_data.get('sector', 'N/A')}

Generated by ARISE FundMatch · Eligibility: {grant_data.get('eligibility_score', 0)}%
    """
    return content.encode('utf-8')

def generate_bbee_affidavit_template(user_data: dict, business_data: dict) -> bytes:
    content = f"""
B-BBEE AFFIDAVIT TEMPLATE
===========================
I, {user_data.get('full_name', '________________')}, hereby declare that:

1. I am the sole/majority owner of {business_data.get('business_name', '________________')}
2. The business has an annual turnover of less than R10 million
3. The business qualifies as an Exempt Micro Enterprise (EME)
4. I am a South African citizen / permanent resident

Signature: ________________
Date: ________________
Commissioner of Oaths: ________________

[This is a template only. Please have this notarised before submission.]

Generated by ARISE LaunchPad
    """
    return content.encode('utf-8')