from sqlalchemy import (
    Column, String, Boolean, DateTime, Enum,
    Text, Integer, Float, ForeignKey, JSON
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import uuid
import enum

from backend.config.database import Base


class SessionStatus(str, enum.Enum):
    SCHEDULED = "scheduled"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    NO_SHOW = "no_show"


class MentorProfile(Base):
    """
    Experienced professionals offering mentorship on ARISE.
    Mentors can be individuals or corporates fulfilling B-BBEE ED obligations.
    """
    __tablename__ = "mentor_profiles"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), unique=True, nullable=False)

    # Professional background
    current_title = Column(String, nullable=True)
    current_company = Column(String, nullable=True)
    years_experience = Column(Integer, nullable=True)
    industry = Column(String, nullable=True)
    bio = Column(Text, nullable=True)
    linkedin_url = Column(String, nullable=True)

    # Mentorship details
    mentorship_areas = Column(JSON, default=list)   # e.g. ["fundraising", "marketing", "tech"]
    preferred_stages = Column(JSON, default=list)   # Which business stages they prefer
    preferred_sectors = Column(JSON, default=list)  # Which sectors they focus on
    languages = Column(JSON, default=list)          # Languages they mentor in
    max_mentees = Column(Integer, default=3)        # How many active mentees at once

    # Availability
    is_available = Column(Boolean, default=True)
    session_duration_minutes = Column(Integer, default=60)
    sessions_per_month = Column(Integer, default=4)
    available_days = Column(JSON, default=list)     # ["monday", "wednesday", "friday"]

    # B-BBEE Enterprise Development
    # If linked to a corporate, sessions count toward their ED spend
    is_bbee_linked = Column(Boolean, default=False)
    linked_employer_id = Column(String, ForeignKey("employer_profiles.id"), nullable=True)
    ed_rate_per_session = Column(Float, nullable=True)  # Amount corporate pays per session

    # Aggregate stats
    total_sessions = Column(Integer, default=0)
    total_mentees = Column(Integer, default=0)
    average_rating = Column(Float, default=0.0)
    is_verified = Column(Boolean, default=False)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    sessions = relationship("MentorSession", back_populates="mentor", cascade="all, delete-orphan")


class MentorSession(Base):
    """
    A scheduled or completed mentorship session between a mentor and entrepreneur.
    Session notes auto-generated by Huawei NLP after completion.
    """
    __tablename__ = "mentor_sessions"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    mentor_id = Column(String, ForeignKey("mentor_profiles.id"), nullable=False)
    mentee_id = Column(String, ForeignKey("users.id"), nullable=False)

    # Scheduling
    scheduled_at = Column(DateTime, nullable=False)
    duration_minutes = Column(Integer, default=60)
    meeting_link = Column(String, nullable=True)    # Huawei Meeting link
    status = Column(Enum(SessionStatus), default=SessionStatus.SCHEDULED)

    # Agenda — what the session covers
    agenda = Column(Text, nullable=True)
    focus_areas = Column(JSON, default=list)

    # Post-session
    completed_at = Column(DateTime, nullable=True)
    # AI-generated session notes — Huawei NLP
    ai_session_notes = Column(Text, nullable=True)
    action_items = Column(JSON, default=list)       # List of follow-up actions

    # Ratings
    mentee_rating = Column(Integer, nullable=True)  # 1-5
    mentee_feedback = Column(Text, nullable=True)
    mentor_notes = Column(Text, nullable=True)      # Private mentor notes

    # B-BBEE compliance — logged for corporate ED reporting
    ed_value = Column(Float, nullable=True)         # Rand value of this session
    ed_reported = Column(Boolean, default=False)    # Included in corporate ED report

    # ECS impact — this session adds to mentee's ECS score
    ecs_points_awarded = Column(Integer, default=25)
    ecs_points_applied = Column(Boolean, default=False)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    mentor = relationship("MentorProfile", back_populates="sessions")